spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.ketu.zjh:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
logging:
  level:
    com.example.demo: debug
