
spring:
  rabbitmq:
    host: mq.ketu.zjh
    port: 5672
    username: test
    password: test
    virtual-host: oscphost
    publisher-returns: true
    publisher-confirm-type: simple
    test:
      queue: direct-string-queue
      exchange: direct-string-exchange
      routing-key: testRoutingKey
server:
  port: 8081
